/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConsultationsRouteImport } from './routes/consultations'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReferralsIndexRouteImport } from './routes/referrals.index'
import { Route as ReferralsNewRouteImport } from './routes/referrals.new'
import { Route as ReferralsIdRouteImport } from './routes/referrals.$id'

const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationsRoute = ConsultationsRouteImport.update({
  id: '/consultations',
  path: '/consultations',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsIndexRoute = ReferralsIndexRouteImport.update({
  id: '/referrals/',
  path: '/referrals/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsNewRoute = ReferralsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ReferralsRoute,
} as any)
const ReferralsIdRoute = ReferralsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReferralsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/consultations': typeof ConsultationsRoute
  '/login': typeof LoginRoute
  '/patients': typeof PatientsRoute
  '/referrals/$id': typeof ReferralsIdRoute
  '/referrals/new': typeof ReferralsNewRoute
  '/referrals/': typeof ReferralsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/consultations': typeof ConsultationsRoute
  '/login': typeof LoginRoute
  '/patients': typeof PatientsRoute
  '/referrals/$id': typeof ReferralsIdRoute
  '/referrals/new': typeof ReferralsNewRoute
  '/referrals': typeof ReferralsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/consultations': typeof ConsultationsRoute
  '/login': typeof LoginRoute
  '/patients': typeof PatientsRoute
  '/referrals/$id': typeof ReferralsIdRoute
  '/referrals/new': typeof ReferralsNewRoute
  '/referrals/': typeof ReferralsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/consultations'
    | '/login'
    | '/patients'
    | '/referrals/$id'
    | '/referrals/new'
    | '/referrals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/consultations'
    | '/login'
    | '/patients'
    | '/referrals/$id'
    | '/referrals/new'
    | '/referrals'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/consultations'
    | '/login'
    | '/patients'
    | '/referrals/$id'
    | '/referrals/new'
    | '/referrals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRoute
  ConsultationsRoute: typeof ConsultationsRoute
  LoginRoute: typeof LoginRoute
  PatientsRoute: typeof PatientsRoute
  ReferralsIndexRoute: typeof ReferralsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultations': {
      id: '/consultations'
      path: '/consultations'
      fullPath: '/consultations'
      preLoaderRoute: typeof ConsultationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals/': {
      id: '/referrals/'
      path: '/referrals'
      fullPath: '/referrals/'
      preLoaderRoute: typeof ReferralsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals/new': {
      id: '/referrals/new'
      path: '/new'
      fullPath: '/referrals/new'
      preLoaderRoute: typeof ReferralsNewRouteImport
      parentRoute: typeof ReferralsRoute
    }
    '/referrals/$id': {
      id: '/referrals/$id'
      path: '/$id'
      fullPath: '/referrals/$id'
      preLoaderRoute: typeof ReferralsIdRouteImport
      parentRoute: typeof ReferralsRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRoute,
  ConsultationsRoute: ConsultationsRoute,
  LoginRoute: LoginRoute,
  PatientsRoute: PatientsRoute,
  ReferralsIndexRoute: ReferralsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
